mybatis-plus:
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    mapUnderscoreToCamelCase: true
    #MyBatis 自动映射策略，通过该配置可指定 MyBatis 是否并且如何来自动映射数据表字段与对象的属性
    autoMappingBehavior: full
    #MyBatis 自动映射时未知列或未知属性处理策略，通过该配置可指定 MyBatis 在自动映射过程中遇到未知列或者未知属性时如何处理
    autoMappingUnknownColumnBehavior: none
    #指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法，通常运用于有 Map.keySet() 依赖或 null 值初始化的情况。
    callSettersOnNulls: true

  global-config:
    #是否控制台 print mybatis-plus 的 LOGO  //丑拒，完全不知道意义何在
    banner: false
    #***是否初始化 SqlRunner(com.baomidou.mybatisplus.extension.toolkit.SqlRunner)
    enable-sql-runner: false
    #全局配置
    db-config:
      #全局默认主键类型
      id-type: ASSIGN_ID
      #逻辑删除字段
      logic-delete-field: removed
      #逻辑未删除值
      logic-not-delete-value: 1
      #逻辑已删除值
      logic-delete-value: 0